document.addEventListener("DOMContentLoaded", function () {
    const greetings = [
        "Hey, beautiful! 💖",
        "Good to see you, my love! 😘",
        "Hello, sunshine! ☀️",
        "My day just got better seeing you here! 💫",
        "You're the most amazing person ever! 💕",
        "Guess who's the cutest person alive? You! 🥰",
        "Hey love, I hope you're smiling today! 😊",
        "Welcome, my angel! 😇",
        "You make my world magical! ✨",
        "Hey, gorgeous! 🌸",
        "Hello, my forever person! ❤️",
        "You're my favorite notification today! 📩",
        "The stars shine brighter when you're around! 🌟",
        "Hey cutie, miss me? 😉",
        "Your smile is my favorite thing! 😍",
        "Hi, my love! Sending you virtual hugs! 🤗",
        "You're looking absolutely stunning today! 😘",
        "Hello, my princess! 👑",
        "Every day is brighter because of you! ☀️",
        "You're my dream come true! 💭💖",
        "My heart races just thinking about you! 💓",
        "Hey there, my star! 🌠",
        "Hope you have the best day ever! 🌈",
        "Just dropping by to say I love you! 💕",
        "Your love is my greatest gift! 🎁💖",
        "Hey soulmate! 💞",
        "You're the reason my world is so beautiful! 🌺",
        "You light up my life! 💡",
        "You're my favorite person, always! 😍",
        "I wish I could hug you right now! 🤗💖",
        "Hey, did I tell you today how much I love you? 😘",
        "No words, just LOVE! ❤️",
        "You're my heart's favorite melody! 🎶💘",
        "Every moment with you is special! ⏳💕",
        "You're the sweetest thing in my life! 🍭💖",
        "Hey my love, I hope today is amazing for you! 🌟",
        "You’re my lucky charm! 🍀",
        "I love you more than yesterday! 💗",
        "You are loved, always! 💕",
        "Your happiness is my mission! 🚀❤️",
        "You're my favorite daydream! 🌙",
        "Life is better with you in it! 🌼",
        "Can’t stop thinking about you! 🧡",
        "You make my heart smile! 😊💖",
        "You're my sunshine on a rainy day! ☔🌞",
        "Hey, cutie! You’re the best part of my life! 💜",
        "I cherish you more than words can say! 💕",
        "You're my home, my happiness, my everything! 🏡❤️",
        "You + Me = Forever! 🔗💖",
        "A million kisses for you! 😘😘😘",
        "You’re my light in the darkness! 🔥",
        "I love you to the moon and back! 🌙💖",
        "You're my cosmic love! 🌌❤️",
        "Your love makes my world magical! ✨",
        "You’re my universe! 🌠💜",
        "You're a blessing in my life! 💖",
        "You are my best adventure! 🌍💞",
        "Waking up knowing you’re mine is the best! ☀️💕",
        "You're my heartbeat! ❤️💓",
        "Just thinking about you makes me happy! 😊",
        "You complete me! 💑💞",
        "You are my shooting star! 🌠✨",
        "No distance can keep us apart! 🥰",
        "You're my favorite human! 💖",
        "You are my sweetest love story! 📖💕",
        "My world revolves around you! 🌎💖",
        "You're my wish come true! 🌠💖",
        "Every second with you is a gift! 🎁💞",
        "You mean everything to me! 💖",
        "Hey Beautiful ❤️", "Good Morning, Sunshine ☀️", "Hi Love! 💕", "Hello, My Angel 😇", 
        "Hey Cutie! 😘", "My Queen 👑, Welcome!", "Hey Gorgeous! 💖", "Rise and shine, my love ☀️",
        "Hello my soulmate 💑", "Hey, my heart! ❤️", "Hi lovebug 🐞", "Hey my cuddle bear 🧸",
        "Hey my queen, you rule my heart 👑", "Hey my world! 🌍", "Hey baby! 😘", "Hello, my sunshine! ☀️",
        "Hey, my perfect one! 😍", "Hey sweetie, your smile is magic! 🪄", "Hey angel, did you fly from heaven? 😇"
    ];

    const messages = [
        "“You are enough just as you are.” – Meghan Markle 💖",
        "“Every day may not be good, but there’s something good in every day.” 🌈",
        "“You’re braver than you believe, stronger than you seem, and smarter than you think.” 💪",
        "“Happiness is not out there, it’s in you.” 🌟",
        "“Sometimes the smallest things take up the most room in your heart.” 🧡",
        "“Believe in yourself and you will be unstoppable.” 🚀",
        "“You are a masterpiece in progress.” 🎨",
        "“Love yourself first, and everything else falls into place.” 💕",
        "“Keep shining, because the world needs your light.” ✨",
        "“You make my world beautiful, just by being in it.” 😍",
        "“Life is a journey, enjoy the ride.” 🚗",
        "“If you can dream it, you can do it.” 💭",
        "“Smile! It confuses people.” 😁",
        "“You are stronger than your struggles.” 💪",
        "“When life gives you lemons, make lemonade!” 🍋",
        "“You are my reason to smile every day.” 😊",
        "“Every love story is beautiful, but ours is my favorite.” 💕",
        "“Your love makes me the happiest person alive.” 💖",
        "“One day, we will look back and smile at how far we’ve come.” 🛤️",
        "“I love you more than words can ever say.” 💗",
        "“You’re my happy place.” 🏡💕",
        "“Distance means so little when someone means so much.” 🌎💞",
        "“You are the peanut butter to my jelly.” 🥪💖",
        "“You are my sunshine on a cloudy day.” ☀️",
        "“Your love is my superpower.” 🦸‍♂️💖",
        "“You make my heart do a happy dance.” 💃🕺",
        "“With you, every moment is special.” 💫",
        "“There’s nothing in the world I’d rather do than love you.” 💖",
        "“I love you more than pizza. And that’s saying something.” 🍕😆",
        "“You are the best thing that ever happened to me.” 💕",
        "“Home is wherever I’m with you.” 🏡❤️",
        "“You are my greatest adventure.” 🌍💖",
        "“The stars shine brighter when you smile.” ✨",
        "“Every day I spend with you is my favorite day.” 💞",
        "“Life’s too short to be serious all the time… so if you can’t laugh at yourself, call me—I’ll do it for you.” 😂",
        "“Some people graduate with honors, I am just honored to graduate.” 🎓😆",
        "“Life is short. Smile while you still have teeth.” 😁",
        "“You and I are like WiFi… better when we’re connected.” 📶❤️",
        "You make my world brighter every day 💖", "Did you know? You're the cutest person on Earth! 🌍💕",
        "One smile from you can melt my heart 😊❤️", "Believe in yourself, love! You are amazing 💪✨",
        "Why don’t skeletons fight? Because they don’t have the guts! 😂", "You are loved more than you imagine 💞",
        "You are stronger than you think! 💪❤️", "You are the most beautiful part of my life 😘",
        "You make my heart race faster than a Ferrari 🚗💨", "You're my favorite human in the universe! 🌌💕",
        "Even on bad days, you make me smile 😊", "You have the kindest heart, and I adore you ❤️",
        "Your love is my favorite feeling 💓", "You are my safe place, always 💖", "You are my answered prayer 💕",
        "You're a magician because whenever I look at you, everything disappears except you! 🎩✨", 
        "I wish I could pause time when I'm with you! ⏳❤️", "I can't wait to spend forever with you 💍❤️",
        "You're my best hello and my hardest goodbye 💕", "Without you, my world would be black and white 🎨❤️",
        "You are my favorite hello and hardest goodbye 💞"
    ];

    document.getElementById("greeting").textContent = greetings[Math.floor(Math.random() * greetings.length)];
    document.getElementById("message").textContent = messages[Math.floor(Math.random() * messages.length)];
});
